Add translation infrastructure and translateComment API
Catrobat/Catroweb pull request #1674
Opened 2021-05-29 20:47 UTC by danielzhang130

- Add TranslationDelegate to handle multiple translation APIs and for error handling
- More features like statistics and caching can be added to TranslationDelegate
- Add translateComment API endpoint
- Add relevant tests
- Fix bug with php == and ===

---
### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroweb-Symfony/blob/develop/.github/contributing.md) and [wiki pages](https://github.com/Catrobat/catroweb-Symfony/wiki/) of this repository.

- [ ] Include the name and id of the Jira ticket in the PR’s title eg.: `SHARE-666 The devils ticket`
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no warnings and errors 
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Verify that all tests are passing (CI), if not please state the test cases in the [section](#Tests) below
- [x] Perform a self-review of the changes
- [x] Stick to the project’s git workflow (rebase and squash your commits)
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] Put your ticket into the `Code Review` section in [Jira](https://jira.catrob.at/)
- [ ] Post a message in the *#catroweb* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer
- [ ] Check that your pull request has been successfully deployed to https://web-test-1.catrob.at/

### Additional Description

This PR is part of adding translation functionality to projects and comments on Catroweb. For more info, join the discussion on #uwaterloo-project slack channel.

### Tests - additional information

2021-05-30 15:06 UTC, dmetzner requested changes

2021-05-30 15:06 UTC, dmetzner commented on tests/phpUnit/Translation/TranslationDelegateTest.php
> +    $invalid_code = [
Would be a good use case for a dataprovider

2021-05-30 15:06 UTC, dmetzner commented on src/Catrobat/Controller/Web/CommentsController.php
> +  public function translateCommentAction(TranslationDelegate $translationDelegate): Response
snake_case

2021-05-30 15:06 UTC, dmetzner commented on src/Catrobat/Controller/Web/CommentsController.php
> +      return new Response('No comment found for this id '.$_GET['CommentId'], Response::HTTP_BAD_REQUEST);
This enables XSS attacks. Never directly use user input to build a response. Could be used for example for phishing

![image](https://user-images.githubusercontent.com/40868718/120106568-cbc90400-c15d-11eb-934f-e937a33801e5.png)

2021-05-30 15:06 UTC, dmetzner commented on src/Catrobat/Controller/Web/CommentsController.php
> +    $source_language = $_GET['SourceLanguage'] ?? null;
![image](https://user-images.githubusercontent.com/40868718/120106693-632e5700-c15e-11eb-91bd-658eb7003c98.png)

2021-05-30 15:06 UTC, dmetzner commented on src/Catrobat/Controller/Web/CommentsController.php
> +      return new Response('No comment found for this id '.$_GET['CommentId'], Response::HTTP_BAD_REQUEST);
404 here

use 400 in case `comment_id` is missing in the request

2021-05-30 15:06 UTC, dmetzner commented on src/Catrobat/Controller/Web/CommentsController.php
> +      return new Response('source and target languages are the same', Response::HTTP_BAD_REQUEST);
again, 400 only if target_language is missing /invalid

use 422 for more specific issues

2021-05-30 15:06 UTC, dmetzner commented on src/Catrobat/Controller/Web/CommentsController.php
> +    $comment = $em->getRepository(UserComment::class)->find($_GET['CommentId']);
please also use snake_case for all request parameters - for consistency with our API (http://developer.catrobat.org/Catroweb-API/) to ease the transfer in the future

2021-05-30 15:06 UTC, dmetzner commented on src/Catrobat/Controller/Web/CommentsController.php
> +   * @Route("/translateComment", name="translate_comment", methods={"GET"})
/translate/comment/{id}

2021-05-30 15:06 UTC, dmetzner commented on src/Catrobat/Controller/Web/CommentsController.php
> +  public function translateCommentAction(TranslationDelegate $translationDelegate): Response
add 

`int id, Request $request`

2021-05-30 15:06 UTC, dmetzner commented on src/Catrobat/Controller/Web/CommentsController.php
> +    $source_language = $_GET['SourceLanguage'] ?? null;
use $request with query get instead of $_GET for some internal validations in the background

2021-05-31 14:48 UTC, danielzhang130 commented on src/Catrobat/Controller/Web/CommentsController.php
> +      return new Response('No comment found for this id '.$_GET['CommentId'], Response::HTTP_BAD_REQUEST);
in this new route /translate/comment/{id}, if id is not provided, the route will not match

2021-05-31 15:04 UTC, dmetzner approved these changes

2021-05-31 15:05 UTC, merged