Translate Program Comment Section
Catrobat/Catroweb pull request #1717
Opened 2021-06-08 16:48 UTC by JoshuaSchaefer

---
### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroweb-Symfony/blob/develop/.github/contributing.md) and [wiki pages](https://github.com/Catrobat/catroweb-Symfony/wiki/) of this repository.

- [ ] Include the name and id of the Jira ticket in the PR’s title eg.: `SHARE-666 The devils ticket`
- [ ] Choose the proper base branch (*develop*)
- [ ] Confirm that the changes follow the project’s coding guidelines
- [ ] Verify that the changes generate no warnings and errors 
- [ ] Verify to commit no other files than the intentionally changed ones
- [ ] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Verify that all tests are passing (CI), if not please state the test cases in the [section](#Tests) below
- [ ] Perform a self-review of the changes
- [ ] Stick to the project’s git workflow (rebase and squash your commits)
- [ ] Verify that your changes do not have any conflicts with the base branch
- [ ] Put your ticket into the `Code Review` section in [Jira](https://jira.catrob.at/)
- [ ] Post a message in the *#catroweb* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer
- [ ] Check that your pull request has been successfully deployed to https://web-test-1.catrob.at/

### Additional Description
The program comment section has been updated to utilize the new iTranslate API and languages API to translate user-generated content. Now, when the translate button is selected, a new translation section will appear with the original content translated to the user's preferred language using the iTranslate API. Within the new translation section, there is also a statement which displays the translation provider, the source language, and the target language.

Additional information on the UI design can be found in the original mockup document through the following link.
https://docs.google.com/document/d/1ELqaGX_zIUMP5p8bcGcGhIe8gDj55ITANxYYuFRgePQ/edit?usp=sharing

### Tests - additional information
Updated the Behat translation tests for comment sections to select the translation button and check if the new translation section opens as intended. These new tests replace the previous tests which checked if the href attribute was updated properly.

2021-06-09 05:35 UTC, dmetzner commented on translations/catroweb.en.yml
> +  showTranslation: Show Translation
Show translation*
 We try to be grammatically correct with upper/lowercase

2021-06-09 05:35 UTC, dmetzner commented on translations/catroweb.en.yml
> +  hideTranslation: Hide Translation
Hide translation

2021-06-09 07:43 UTC, dmetzner requested changes
Looks good to me. Only the translations have to be "fixed" :)


Edit: Sime screens for UX: @ThorstenBandel 
![image](https://user-images.githubusercontent.com/40868718/121314111-56042b80-c907-11eb-894d-5bab0aadbe99.png)
![image](https://user-images.githubusercontent.com/40868718/121314607-cd39bf80-c907-11eb-9608-e1d5089f02bd.png)

2021-06-09 09:52 UTC, ThorstenBandel commented
Looks, good, just one thing: can you User the report icon from google fonts? https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Areport

And please dont make the icon red but gray as in the mockups. We dont want to emphatize on the reporting

2021-06-09 18:19 UTC, JoshuaSchaefer commented
> Looks good, just one thing: can you User the report icon from google fonts? https://fonts.google.com/icons?selected=Material%20Icons%20Outlined%3Areport
> 
> And please dont make the icon red but gray as in the mockups. We dont want to emphatize on the reporting

I think this work might be out of the scope of this PR. This PR is just to add the ability to translate a comment with the new API and replace the original comment with the new translated comment on the UI. I don't believe there are any changes to the existing report icon or any functionality related to it.

2021-06-09 18:27 UTC, JoshuaSchaefer commented on translations/catroweb.en.yml
> +  showTranslation: Show Translation
Updated to "Show translation"

2021-06-09 18:28 UTC, JoshuaSchaefer commented on translations/catroweb.en.yml
> +  hideTranslation: Hide Translation
Updated to "Hide translation"

2021-06-12 14:30 UTC, dmetzner approved these changes

2021-06-12 14:30 UTC, merged