SHARE-527: Media Library Search Fix
Catrobat/Catroweb pull request #3072
Opened 2022-06-17 09:24 UTC by schaubes

---
### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroweb-Symfony/blob/develop/.github/contributing.md) and [wiki pages](https://github.com/Catrobat/catroweb-Symfony/wiki/) of this repository.

- [x] Include the name and id of the Jira ticket in the PR’s title eg.: `SHARE-666 The devils ticket`
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no warnings and errors 
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [ ] Verify that all tests are passing (CI), if not please state the test cases in the [section](#Tests) below
- [x] Perform a self-review of the changes
- [x] Stick to the project’s git workflow (rebase and squash your commits)
- [x] Verify that your changes do not have any conflicts with the base branch
- [ ] Put your ticket into the `Code Review` section in [Jira](https://jira.catrob.at/)
- [ ] Post a message in the *#catroweb* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer
- [ ] Check that your pull request has been successfully deployed to https://web-test-1.catrob.at/

### Additional Description
Update media library to use new API and implement search

### Tests - additional information
No additional information

2022-07-15 08:21 UTC, dmetzner approved these changes

2022-07-15 08:21 UTC, dmetzner commented on assets/js/custom/MediaLib.js
> +    if ($.inArray(flavor, acceptedFlavors) === -1) {
It would be great if we could get rid of jquery and its overhead.
you could use indexOf here

2022-07-15 08:24 UTC, dmetzner requested changes
https://pr3072-web.catrobat.ist.tugraz.at/app/media-library/looks/search/P

Looks like the counter does not work as expected?
![image](https://user-images.githubusercontent.com/40868718/179184083-40ee699c-8a9d-4952-9f79-d6773f284c2f.png)

2022-07-15 08:26 UTC, dmetzner commented on assets/js/custom/MediaLib.js
> +    if ($.inArray(flavor, acceptedFlavors) === -1) {
Note: no need to change it now; we can remove jquery in a separate user story

2022-07-19 10:52 UTC, schaubes commented
fixed search count and the jquery snippet, plus some css to enable the media queries again

2022-07-20 05:38 UTC, dmetzner approved these changes

2022-07-20 05:39 UTC, merged