SHARE-74 Use flavor-specific App-Store links (luna fix)
Catrobat/Catroweb pull request #316
Opened 2019-06-21 21:18 UTC by mfuerni

Set flavor-specific Google Play Store URL as theme variable.
Use this variable on all locations.

Change iOS home/help card to Discord card for Luna flavor.

2019-06-21 21:22 UTC, mfuerni commented
@bernadettespieler Should I remove the iOS link for luna in the footer as well?

2019-06-30 05:09 UTC, dmetzner requested changes
Please also add the Discord-Logo-White.svg

2019-07-01 16:19 UTC, dmetzner approved these changes

2019-08-08 18:26 UTC, mfuerni commented
Now the link in the footer to the iOS App store is only shown on the 'pocketcode' flavor.

2019-08-09 07:50 UTC, merged