SHARE-122 readded & fixed codeview object image
Catrobat/Catroweb pull request #352
Opened 2019-08-22 07:53 UTC by dmetzner

on every project page when looking at the code view there should
now be the correct object image displayed for each object.
Also added a fontawesome icon (times) when there is no image found.

2019-08-22 07:54 UTC, dmetzner commented
![image](https://user-images.githubusercontent.com/40868718/63496775-c6d41c80-c4c2-11e9-9470-bd7445b21939.png)

2019-08-25 22:54 UTC, mfuerni requested changes
The aspect ratio of the images is not kept. Maybe we should change that.
Do we need any tests for the presence of the correct image?

✓ All tests are passed

2019-08-25 22:54 UTC, mfuerni commented on src/Catrobat/Services/CatrobatCodeParser/ParsedObjectAsset.php
> +    $this->file_name = str_replace('#', '%23', $this->file_name);
Shouldn't we use `urlencode()` here instead? Or better use twig `url_encode` filter instead.

2019-08-25 22:54 UTC, mfuerni commented on templates/Program/codeview.html.twig
> +      <img src="{{ asset('./'~path~'/'~scene_name~'/images/'~object.getLooks()[0].getFileName()) }}" class="object-icon">
`path` ends with `/`, so use `~path~scene_name~` instead

2019-08-25 22:54 UTC, mfuerni commented on templates/Program/codeview.html.twig
> +              <img src="{{ asset('./'~path~'/'~scene_name~'/images/'~script.getLookFileName()) }}"
`path` ends with `/`, so use `~path~scene_name~` instead

2019-08-25 22:54 UTC, mfuerni commented on templates/Program/codeview.html.twig
> +                  <img src="{{ asset('./'~path~'/'~scene_name~'/images/'~brick.getLookFileName()) }}"
`path` ends with `/`, so use `~path~scene_name~` instead

2019-08-25 22:54 UTC, mfuerni commented on src/Catrobat/Services/CatrobatCodeParser/ParsedObjectAsset.php
> +    if (count($this->file_name = $asset_xml_properties['name']) !== 0)
I don't get the idea of these two changes (if condition + body).

I think the following code is enough for this method, since name and fileName are always attributes, not nodes.
```
    $this->asset_xml_properties = $asset_xml_properties;
    $this->name = $asset_xml_properties[Constants::NAME_ATTRIBUTE];
    $this->file_name = urlencode($asset_xml_properties['fileName']);
```

2019-08-26 08:56 UTC, dmetzner commented on src/Catrobat/Services/CatrobatCodeParser/ParsedObjectAsset.php
> +    if (count($this->file_name = $asset_xml_properties['name']) !== 0)
I have tested it; it is enough. But I have used rawurlencode which used '%20' instead of '+'.

2019-08-26 09:01 UTC, dmetzner commented
changed css to object-fit: cover to keep the aspect ratio.
added a twig extension to check if files exist. If correct images don't exist the object not found placeholder is shown.

2019-08-26 09:22 UTC, dmetzner commented on src/Catrobat/Services/CatrobatCodeParser/ParsedObjectAsset.php
> +    if (count($this->file_name = $asset_xml_properties['name']) !== 0)
just had to change the outdated code.xml and unit test.

2019-08-27 07:40 UTC, dmetzner commented
- added checks for scripts, bricks and sounds, 
- fixed brick, scripts, sound getFileName
- outsourced codeview js

2019-08-31 11:46 UTC, mfuerni requested changes
Just two minor fixes, then I can approve it.

2019-08-31 11:46 UTC, mfuerni commented on src/Catrobat/Services/CatrobatCodeParser/Scripts/WhenBGChangeScript.php
> +        $this->look_file_name = $this->brick_xml_properties->look['fileName'];
`brick_xml_properties` does not exist in class `Script`. Must be changed to `script_xml_properties`.

2019-08-31 11:46 UTC, mfuerni commented on templates/Program/codeview.html.twig
> +                <img src="{{ asset('./'~path~scene_name~'/images/'~brick.getLookFileName()) }}"
I think this line (75) should be removed.

2019-08-31 16:14 UTC, mfuerni approved these changes

2019-10-01 09:00 UTC, merged