SHARE-157
Catrobat/Catroweb pull request #431
Opened 2020-02-11 10:40 UTC by FelixAuf

Admins can add example programs via the admin panel, these programs will be visible in the chosen flavor (either Embroidery or Arduino), similarly to the featured programs. Headers for "Featured" and "Examples" are set invisible if there are no such projects. Also added help text for image constraints in Sonata.

2020-02-14 13:40 UTC, dmetzner requested changes
As discussed.

2020-03-27 08:15 UTC, dmetzner requested changes
The git problems must be fixed

2020-04-01 14:58 UTC, dmetzner requested changes
1) Please add more tests for the admin interface
2) The new API also has the possibility to ask for all example projects.
    Add tests similar to `tests/behat/features/api/projects/get_most_downloaded_projects.feature` for the example projects.

3) There seems to a bug concerning the flavor change:

luna has no newest project section. But when I switch an example project from pocketcode to luna - luna suddenly has a newest project + recommended section on the homepage in addition to the example section.

before:
![image](https://user-images.githubusercontent.com/40868718/78151494-efe56400-7438-11ea-9af9-f15ccdfae0cc.png)
 after:
![image](https://user-images.githubusercontent.com/40868718/78152362-fcb68780-7439-11ea-960b-2b9881568348.png)

2020-04-01 14:58 UTC, dmetzner commented on tests/behat/features/admin/example_projects.feature
> +      | 3  | program 3 | pocketcode | no      |
add a test:
- set a project to an example project 
- reset an example project to a normal project
- change the flavor of example project

2020-04-01 15:03 UTC, dmetzner requested changes
Changes requested from po review:

- only list example projects
- add a mask for new example project creation
 -- option to set a flavor (this allow to use the same project for different flavors as example project)
 -- option to set a thumbnail directly (every flavor might use a different thumbnail for the same project)
should be similar to Featured projects...
![image](https://user-images.githubusercontent.com/40868718/78152870-b3b30300-743a-11ea-9519-4736f98c3da2.png)

2020-05-05 07:03 UTC, dmetzner requested changes
I have highlighted some minor stuff.

All in all, it already works quite nicely. Also great that it is already integrated and tested in the new API.

- the old api stuff should be removed - then also the old api tests should pass again.
- ...

2020-05-05 07:03 UTC, dmetzner commented on src/Entity/Program.php
> +    return false;
always returning false? Was this intended?

2020-05-05 07:03 UTC, dmetzner commented on templates/Index/index.html.twig
> +      <h1>{{ "programs.example"|trans({}, "catroweb") }}</h1>
```
should be a <h2>

there must be only one h1 per page
```

2020-05-05 07:03 UTC, dmetzner commented on package-lock.json
>      "@babel/code-frame": {
We should really try to update npm only in explicit PRs. Else there will always be merge conflicts.

2020-05-05 07:03 UTC, dmetzner commented on src/Catrobat/Controller/Api/ListProgramsController.php
> +  /**
the new Projects API is already finished - no need to add something to the old one.
this call can be removed.

2020-05-05 07:03 UTC, dmetzner commented on src/Catrobat/Controller/Api/ListProgramsController.php
> +    elseif ('example' === $sortBy)
also not needed

2020-05-05 07:03 UTC, dmetzner commented on src/Catrobat/Forms/ExampleImageConstraint.php
> +  public int $required_width = 512;
I think this constraint can be dropped.
Project thumbnails are "optimized" during the project upload. (take a look into the ScreenshotRepository.php class)

If possible reuse the same methods. 

@SasaDermanovic What is your opinion about it? Since you are reworking the image optimizations.

2020-05-05 07:03 UTC, dmetzner commented on src/Catrobat/Listeners/View/ProgramListSerializer.php
> +          {
that's old API and not really needed. Also, most of the logic would not have been needed if the projects thumbnails were initialized correctly

2020-05-05 07:03 UTC, dmetzner commented on src/Catrobat/Services/ExampleImageRepository.php
> +    $this->path = $path;
```
phpcpd 5.0.2 by Sebastian Bergmann.

Found 1 clones with 28 duplicated lines in 2 files:

  - /github/workspace/src/Catrobat/Services/ExampleImageRepository.php:22-50 (28 lines)
    /github/workspace/src/Catrobat/Services/FeaturedImageRepository.php:22-50

0.06% duplicated lines out of 43502 total lines of code.
Average size of duplication is 28 lines, largest clone has 28 of lines

```
https://github.com/Catrobat/Catroweb-Symfony/pull/431/checks?check_run_id=642604864

2020-05-05 07:03 UTC, dmetzner commented on src/Catrobat/Services/ExampleImageRepository.php
> +class ExampleImageRepository
```
 ------ ----------------------------------------------------------------------- 
  Line   src/Catrobat/Services/ExampleImageRepository.php                       
 ------ ----------------------------------------------------------------------- 
  37     Parameter #1 $id of method                                             
         App\Catrobat\Services\ExampleImageRepository::generateFileNameFromId(  
         ) expects string, int given.                                           
  42     Parameter #1 $id of method                                             
         App\Catrobat\Services\ExampleImageRepository::generateFileNameFromId(  
         ) expects string, int given.                                           
  56     Parameter #1 $id of method                                             
         App\Catrobat\Services\ExampleImageRepository::generateFileNameFromId(  
         ) expects string, int given.                                           
 ------ ----------------------------------------------------------------------- 
```

2020-05-05 07:03 UTC, dmetzner commented on src/Catrobat/Listeners/View/ProgramListSerializer.php
> +          $new_program['Extension'] = $program->getImageType();
```
 ------ ----------------------------------------------------------------- 
  Line   src/Catrobat/Listeners/View/ProgramListSerializer.php            
 ------ ----------------------------------------------------------------- 
  61     Call to an undefined method App\Entity\Program::getImageType().  
  63     Call to an undefined method App\Entity\Program::getProgram(). 
```

2020-05-05 17:12 UTC, SasaDermanovic commented on src/Catrobat/Forms/ExampleImageConstraint.php
> +  public int $required_width = 512;
Yes, that would be my verdict too, since the constraint is irrelevant and therefore can be dropped.

2020-05-12 17:10 UTC, dmetzner approved these changes

2020-05-12 17:10 UTC, merged