Privacy policy safeguard url
Catrobat/Catroweb pull request #432
Opened 2020-02-11 17:31 UTC by SasaDermanovic

-Added privacy_policy.feature
-Added privacy policy route
-Added privacy_policy var instead of hardcoded URL

2020-02-11 19:13 UTC, HCrane requested changes
Rebase this commit to current develop please!

2020-02-11 20:02 UTC, SasaDermanovic commented
Rebased

2020-02-12 17:29 UTC, dmetzner approved these changes

2020-02-13 16:35 UTC, HCrane approved these changes

2020-02-13 20:34 UTC, merged