SHARE-166 Followers and other whom I follow not all shown
Catrobat/Catroweb pull request #457
Opened 2020-03-03 16:36 UTC by hungryapeman

---
### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroweb-Symfony/blob/develop/.github/contributing.md) and [wiki pages](https://github.com/Catrobat/catroweb-Symfony/wiki/) of this repository.

- [X] Include the name and id of the Jira ticket in the PR’s title eg.: `SHARE-666 The devils ticket`
- [X] Choose the proper base branch (*develop*)
- [X] Confirm that the changes follow the project’s coding guidelines
- [X] Verify that the changes generate no warnings and errors 
- [X] Verify to commit no other files than the intentionally changed ones
- [X] Include reasonable and readable tests verifying the added or changed behavior
- [X] Verify that all tests are passing, if not please state the test cases in the [section](#Tests) below
- [X] Perform a self-review of the changes
- [X] Stick to the project’s git workflow (rebase and squash your commits)
- [X] Verify that your changes do not have any conflicts with the base branch
- [X] Put your ticket into the `Code Review` section in [Jira](https://jira.catrob.at/)
- [X] Post a message in the *#catroweb* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### Additional Description
`TODO: Add additional information that is not in your commit-message here`

### Tests - additional information
`TODO: add additional information about testruns here`

2020-03-03 17:30 UTC, dmetzner requested changes
Please just fix some minor stuff and it can be approved.

- Our public routes should always use **app** and not a specific flavor.

2020-03-03 17:30 UTC, dmetzner commented on tests/behat/features/bootstrap/WebFeatureContext.php
> +    $followedUser->setPlainPassword('123456');
use self::DEFAULT_PASSWORD instead ;)

2020-03-03 17:30 UTC, dmetzner commented on tests/behat/features/web/many_follower.feature
> +    And I am on "/pocketcode/user"
use _app_ instead of _pocketcode_

2020-03-03 17:30 UTC, dmetzner commented on tests/behat/features/web/many_follower.feature
> +    When I am on "/pocketcode/user/"
you are already on this page.. use just  When I open the menu

2020-03-03 17:30 UTC, dmetzner commented on tests/behat/features/web/many_follower.feature
> +    And I wait for the page to be loaded
unnecessary wait, you are already on the page and have already waited.

2020-03-06 12:03 UTC, dmetzner approved these changes

2020-03-08 14:05 UTC, HCrane commented
@hungryapeman Please push the Ticket inside the Jira to Codereview!

2020-03-08 14:05 UTC, merged