SHARE-200 API Get project
Catrobat/Catroweb pull request #506
Opened 2020-04-15 11:01 UTC by JackShahhoud

---
### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroweb-Symfony/blob/develop/.github/contributing.md) and [wiki pages](https://github.com/Catrobat/catroweb-Symfony/wiki/) of this repository.

- [x] Include the name and id of the Jira ticket in the PR’s title
- [x] Choose the proper base branch (*develop*)
- [x] Confirm that the changes follow the project’s coding guidelines
- [x] Verify that the changes generate no warnings and errors 
- [x] Verify to commit no other files than the intentionally changed ones
- [x] Include reasonable and readable tests verifying the added or changed behavior
- [x] Verify that all tests are passing, if not please state the test cases in the [section](#Tests) below
- [x] Perform a self-review of the changes
- [x] Stick to the project’s git workflow (rebase and squash your commits)
- [x] Verify that your changes do not have any conflicts with the base branch
- [x] Put your ticket into the `Code Review` section in [Jira](https://jira.catrob.at/)
- [x] Post a message in the *#catroweb* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

2020-04-15 14:48 UTC, dmetzner requested changes
It seems like a visibility check is missing. Please add it and also 1 or 2 tests for it :)

2020-04-15 14:48 UTC, dmetzner commented on src/Repository/ProgramRepository.php
> +    $query_builder = $this->addDebugBuildCondition($query_builder, $debug_build);
visibility check?

2020-04-27 10:18 UTC, hebesempso approved these changes

2020-04-28 06:10 UTC, dmetzner approved these changes

2020-04-28 06:10 UTC, merged