SHARE-245-Refactoring-Adminarea-SpecialProjects-TemplateProjects
Catrobat/Catroweb pull request #728
Opened 2020-07-13 16:36 UTC by arminpasalic10

- Mosaic view removed
- Projects are now sorted by 'active' in descending order
- Removed filtering by Id, since there is no practical use for it
- Filtering by active-status added
- Wrote test cases for template projects

---
### Your checklist for this pull request
Please review the [contributing guidelines](https://github.com/Catrobat/Catroweb-Symfony/blob/develop/.github/contributing.md) and [wiki pages](https://github.com/Catrobat/catroweb-Symfony/wiki/) of this repository.

- [ X ] Include the name and id of the Jira ticket in the PR’s title eg.: `SHARE-666 The devils ticket`
- [ X ] Choose the proper base branch (*develop*)
- [ X ] Confirm that the changes follow the project’s coding guidelines
- [ X ] Verify that the changes generate no warnings and errors 
- [ X ] Verify to commit no other files than the intentionally changed ones
- [ X ] Include reasonable and readable tests verifying the added or changed behavior
- [ X ] Verify that all tests are passing, if not please state the test cases in the [section](#Tests) below
- [ X ] Perform a self-review of the changes
- [ X ] Stick to the project’s git workflow (rebase and squash your commits)
- [ X ] Verify that your changes do not have any conflicts with the base branch
- [ X ] Put your ticket into the `Code Review` section in [Jira](https://jira.catrob.at/)
- [ X ] Post a message in the *#catroweb* [Slack channel](https://catrobat.slack.com) and ask for a code reviewer

### Additional Description
`TODO: Add additional information that is not in your commit-message here`

### Tests - additional information
`TODO: add additional information about testruns here`

2020-07-19 18:43 UTC, leno12 requested changes
![Screenshot from 2020-07-19 20-47-06](https://user-images.githubusercontent.com/24433786/87882571-0a9c1280-ca01-11ea-9246-96baa3987d84.png)

please remove this

2020-07-19 18:44 UTC, leno12 requested changes
![Screenshot from 2020-07-19 20-44-15](https://user-images.githubusercontent.com/24433786/87882508-a24d3100-ca00-11ea-8bcd-f2061223a660.png)
please remove this new line

2020-07-19 19:26 UTC, leno12 approved these changes
Looks good to me. But please dont update dependencies if you dont need in package.json or composer.json because we have dependabot for that. (dont run npm update command).

2020-07-21 10:24 UTC, dmetzner approved these changes

2020-07-21 10:25 UTC, merged