SHARE-365 Extensions as flavor
Catrobat/Catroweb pull request #785
Opened 2020-07-30 08:18 UTC by dmetzner

Use extension tags to find projects similar to flavor

2020-07-30 09:09 UTC, leno12 requested changes
PR looks nice to me. Just if you can fix the failing test cases it would be great.

2020-07-30 13:16 UTC, HCrane approved these changes
Primarily LGTM but this Version thing needs further ivestigation...@dmetzner would you be so kind to create a research ticket?

2020-07-30 13:16 UTC, HCrane commented on src/Catrobat/Services/TestEnv/DataFixtures/ProjectDataFixtures.php
> +    $project->setLanguageVersion($config['language version'] ?? '0.925');
This needs further investigation!

2020-07-31 06:09 UTC, dmetzner commented on src/Catrobat/Services/TestEnv/DataFixtures/ProjectDataFixtures.php
> +    $project->setLanguageVersion($config['language version'] ?? '0.925');
Done

2020-07-31 07:38 UTC, merged